server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/product
spring.datasource.username=folksy
spring.datasource.password=rout
spring.datasource.driver-class-name=org.postgresql.Driver

management.endpoints.web.exposure.include=mappings,beans,caches,env,metrics,shutdown,auditevents,threaddump
management.endpoint.env.show-values=always
management.endpoint.shutdown.access=unrestricted